//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorFinanciero.Entities
{

    public partial class Archivo
    {
        public int ArchivoId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NombreXLS { get; set; }
        public string NombreTXT { get; set; }
        public string Estado { get; set; }
    
        public virtual Parametro Parametro { get; set; }
    }
}
