//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorFinanciero.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoProducto
    {
        public int IdConcepto { get; set; }
        public int IdProducto { get; set; }
        public string TipoComision { get; set; }
        public decimal Tasa { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public Nullable<decimal> Maximo { get; set; }
        public Nullable<decimal> METasaMax { get; set; }
        public Nullable<decimal> METasaMin { get; set; }
        public Nullable<decimal> MEMin { get; set; }
        public Nullable<decimal> MEMax { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Concepto Concepto { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
