//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladorFinanciero.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoBanco
    {
        public string IdBanco { get; set; }
        public int IdProducto { get; set; }
        public string WebTarifario { get; set; }
        public string Contacto { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
